spring:
  application:
    name: rag-sample

  ai:
    ollama:
      base-url: http://localhost:11431
      chat:
        model: gemma3:4b-it-q4_K_M
    vectorstore:
      pgvector:
        initialize-schema: false
        table-name: vector_store
        dimensions: 1024


  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

  datasource:
    url: jdbc:postgresql://localhost:5432/ragdb
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: validate