spring:
  application:
    name: rag-sample

  ai:
    ollama:
      base-url: http://localhost:11431
      chat:
        model: gemma3:4b-it-q4_K_M
      embedding:
        model: mxbai-embed-large
    vectorstore:
      pgvector:
        initialize-schema: false
        schema-validation: true
        table-name: vector_store
        dimensions: 1024
        index-type: hnsw
        id-type: uuid

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

  datasource:
    url: jdbc:postgresql://localhost:5432/ragdb
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: validate

logging:
  level:
    org.springframework.ai.chat.client.advisor: debug

app:
  advisors:
    history:
      enabled: true
      max-messages: 5
    rag:
      enabled: true